name: Deploy App to AWS Lambda

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: aws-lambda-deployment
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Echo GitHub Environment
        run: |
            echo ${{ env.MESSAGE}}
            echo "Triggered by environment: ${{ github.event_name }}"
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies and build
        run: |
            npm ci
            npm run build
      - name: Package application
        run: npm run package
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Deploy
        run: |
            aws s3 cp ./lambda_layer.zip s3://${{ secrets.S3_BUCKET_LAMBDA_LAYER }}/
            aws s3 sync ./dist/client s3://${{ secrets.S3_BUCKET_WWW_PUBLIC }}/ --delete
            aws lambda update-function-code --function-name ${{ secrets.FUNCTION_NAME }} --zip-file fileb://lambda_function.zip


